### ISSUE TITLE
Провести перемовини з видавцями 

### ISSUE THREAD

**Issue by chmen** [marx-in-ua/das-kapital#115]
Як тільки буде готовий milestone по II тому

**Comment by chmen** [comment]
Лабораторія
Наш Формат
Комубук
Фабула

**Comment by chmen** [comment]
Можемо зустрічатися з кимось з Видавництв, зразу після відпустки

**Comment by denys-potapov** [comment]
Переніс в https://github.com/marx-in-ua/das-kapital/issues/203
