### ISSUE TITLE
LaTeX White text on black page on title page

### ISSUE THREAD

**Issue by denys-potapov** [marx-in-ua/das-kapital#21]
We want that on title page the background was black and text was white. There is a special command bookpaget defined in [style.sty](https://github.com/marx-in-ua/das-kapital/blob/4d2f93a15bc713f11afe90d92571c1a5f6c28af2/tex/style.sty#L96)

How it looks like now
![current](https://user-images.githubusercontent.com/2123712/66156264-021d4b80-e62a-11e9-96e9-c3a73d239da0.png)

How it should be
![expected](https://user-images.githubusercontent.com/2123712/66156265-021d4b80-e62a-11e9-81f0-65ecd459a4fd.png)

The styles are pretty big, but i've created MWE [white.on.black.tex](https://github.com/marx-in-ua/das-kapital/blob/master/tex/issues/white.on.black.tex) so you can focus only on text color.

We use luatex for project building.

**Comment by RaulLima2** [comment]
Hi, guy, How can i help you?

**Comment by denys-potapov** [comment]
Thanks for interest. I've described everything in issue itself, we want
that command *bookpaget* produced white text on black page. You can see the
complete MWE in link above.

сб, 5 жовт. 2019, 14:38 користувач RaulLima2 <notifications@github.com>
пише:

**Comment by RaulLima2** [comment]
Hi, Good Morning, we utilized `\usepackage{xcolor}` and `\pagecolor{black}` , `\color{white}`.

**Comment by denys-potapov** [comment]
Feel free to use. Waiting for your pull request. Just note that only pages generated with bookpaget should be white on black. Thanks in advance.

**Comment by denys-potapov** [comment]
Hi, @RaulLima2 we have a "thank you"  page in book, where we list all the contributors. Can you please write your full name?

**Comment by RaulLima2** [comment]
Yes, Raul Bruno Santos Lima
