### ISSUE TITLE
Check if the issue with paragraph II resolved after render

### ISSUE THREAD

**Issue by chmen** [marx-in-ua/das-kapital#38]
![Рисунок (49)](https://user-images.githubusercontent.com/11498407/137990505-f1f73055-bc78-4907-ba6d-77468c43cea5.png)

**Comment by denys-potapov** [comment]
1) Так и должно быть — после пфбрейка абзацу не нужен отсутп
2) Исправил

![Знімок екрану з 2021-11-30 09-20-07](https://user-images.githubusercontent.com/2123712/144003163-a21e17fc-236d-4aa6-8d19-71820f04e702.png)
