### ISSUE TITLE
Page reference in II

### ISSUE THREAD

**Issue by denys-potapov** [marx-in-ua/das-kapital#41]
tex/ii/_0320.tex

Тут виклад трохи відхиляється від вище поданого (стор. 306--307). - исправить

https://github.com/marx-in-ua/das-kapital/pull/40/files#diff-8366222ff36423ee88cf11ab300c514c1e4ef4b4e1bf9e83a239cd3d631215fbR20

**Comment by chmen** [comment]
<img width="762" alt="Screenshot 2022-07-17 at 08 43 46" src="https://user-images.githubusercontent.com/11498407/179385633-04402cbc-009c-4df7-b416-11c6753be7e6.png">
<img width="772" alt="Screenshot 2022-07-17 at 08 42 36" src="https://user-images.githubusercontent.com/11498407/179385636-ad13d38a-af8b-4569-8d69-21668502f0bc.png">
