### ISSUE TITLE
Як форматувати формулу

### ISSUE THREAD

**Issue by chmen** [marx-in-ua/das-kapital#57]
<img width="1440" alt="Screen Shot 2021-12-13 at 10 47 12 PM" src="https://user-images.githubusercontent.com/11498407/145886941-a4900a70-6e9d-411e-94e8-e722dbf9c695.png">

На практиці виходть що формула 6 х 8 =48 виглядає краще ніж та що обведена червоним, яка ще і розірвана при цьому. хоча у другому випадку формула заключена в $ $

**Comment by denys-potapov** [comment]
Ну, в текущей версии оно выгляди нормально, как будто уже исправлен
![Знімок екрана з 2021-12-14 10-17-01](https://user-images.githubusercontent.com/2123712/145959529-c25ea06b-08d4-4667-969f-8ae2dcdb15ad.png)
о
