### ISSUE TITLE
Правки від Климчука ІІ том

### ISSUE THREAD

**Issue by chmen** [marx-in-ua/das-kapital#99]
![26](https://user-images.githubusercontent.com/2123712/180649609-bcd9a9dd-8aed-4ffe-987a-228bc33f4f4c.jpeg)
![30](https://user-images.githubusercontent.com/2123712/180649611-e12236eb-8446-412a-88ec-a76e286e8bc3.jpeg)
![50 done](https://user-images.githubusercontent.com/2123712/180649613-fe80afa1-7276-4341-970b-178391230036.jpeg)
![52 done](https://user-images.githubusercontent.com/2123712/180649614-59ed3b33-e5ac-4116-a383-e26f1f2b71ba.jpeg)
![118 done](https://user-images.githubusercontent.com/2123712/180649616-d30cce41-623a-4c8d-bc9a-fc05d610f60f.jpeg)
![140](https://user-images.githubusercontent.com/2123712/180649618-2422eab0-a67d-4cfe-863b-e718ba8c9bc0.jpeg)
![145 done](https://user-images.githubusercontent.com/2123712/180649619-ca958314-6f75-44a1-9ad1-a5cb65ea0999.jpeg)
![186 done](https://user-images.githubusercontent.com/2123712/180649620-692a41ad-0975-4af0-9534-b704a141213f.jpeg)
![275 done](https://user-images.githubusercontent.com/2123712/180649621-67660f79-6300-452e-91af-6ba2ab4c85c6.jpeg)
![319 done](https://user-images.githubusercontent.com/2123712/180649623-3b28525e-c3bd-4011-b703-80f07a7ce643.jpeg)
![353 done](https://user-images.githubusercontent.com/2123712/180649626-2e09f8fd-0abd-4bc0-8349-d709b8aed1ff.jpeg)
![357 done](https://user-images.githubusercontent.com/2123712/180649628-64e2b64e-fb99-473e-a963-d84987a71480.jpeg)
![374 done](https://user-images.githubusercontent.com/2123712/180649629-9307d4fe-b77c-45da-9dee-b4a2b2434404.jpeg)
![380 done](https://user-images.githubusercontent.com/2123712/180649631-8a7d6cc3-f395-46c6-8983-dffcb433a404.jpeg)
![384 done](https://user-images.githubusercontent.com/2123712/180649632-eaa94ab8-f997-401e-982c-4cd3bcc0eec3.jpeg)

**Comment by denys-potapov** [comment]
Залив список правок
